# Generated by Django 4.1.1 on 2022-09-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('commands', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('upvote_num', models.IntegerField(default=0)),
                ('downvote_num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'command_set',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tool',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WordIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('command_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_set.commandset')),
            ],
            options={
                'db_table': 'word_index',
                'ordering': ['word'],
            },
        ),
        migrations.AddField(
            model_name='commandset',
            name='tool',
            field=models.ManyToManyField(to='command_set.tool'),
        ),
    ]
