# Generated by Django 4.1.1 on 2022-09-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command_set', '0002_commandset_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandset',
            name='downvote_num',
        ),
    ]
