# Generated by Django 4.1.1 on 2022-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_set', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved_command_set',
            field=models.ManyToManyField(blank=True, null=True, to='command_set.commandset'),
        ),
    ]
