# Generated by Django 4.1.1 on 2022-09-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_set', '0007_alter_tool_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandset',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='commandset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
