# Generated by Django 4.1.1 on 2022-09-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_set', '0008_alter_commandset_options_commandset_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandset',
            name='visited_num',
            field=models.IntegerField(default=0),
        ),
    ]
