# Generated by Django 4.1.1 on 2022-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_set', '0009_commandset_visited_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandset',
            name='description',
        ),
        migrations.AlterField(
            model_name='commandset',
            name='commands',
            field=models.CharField(max_length=1500),
        ),
    ]
